### ISSUE TITLE
EP Reports failed to run during Fri Jun 11th automated run due to VCEP submitter changes

### ISSUE THREAD

**Issue by toneillbroad** [clingen-data-model/clinvar-reports#3]
EP reports run as part of the weekly Friday run of all ClinVar reports (Zero Star, One Star, EP and GenomeConnect). On Fri Jun 11th 2021 the EP reports failed with the following error:

	Traceback (most recent call last):
	  File "./EPReports.py", line 862, in <module>
	    main()
	  File "./EPReports.py", line 860, in main
	    create_files(ExcelDir, excelFile, date, statFile)
	  File "./EPReports.py", line 304, in create_files
	    create_EPfiles(ExcelDir, excelFile, date, workbookStat, worksheetStat0)
	  File "./EPReports.py", line 344, in create_EPfiles
	    tab(EP, EPOrgID, workbook, worksheet0, worksheetStat0, count)
	  File "./EPReports.py", line 557, in create_tab5
	    and varID in HGVSHash and HGVSHash[varID]['GeneSym'] in EPGeneHash[EP]:
	KeyError: 'ClinGen_Rett_and_Angelman_like_Disorders_Vari'

This usually means that the name of the EP submitter of an SCV has changed in the ClinVar files and is not represented in the EP_GeneList.xlsx file that maps genes to EPs.

**Comment by toneillbroad** [comment]
The following VCEP submitter names changed and were not represented properly in the EP_GeneList.xlsx. 

The way to determine the proper name is to download the submission_summary.txt.gz file from ClinVar. Looking at the 'KeyError' line from the error message, we need to search for the submitted name in the submission summary file:

zmore submission_summary.txt.gz | sed '1,16'd | awk -F \t '{print $10}' | sort -u | grep Rett

- Needed to change "Rett ANgelman" to "ClinGen Rett and Angelman-like Disorders Variant Curation Expert Panel, ClinGen" in EP_GeneList.xlsx.
- Needed to change "MHS" VCEP name "ClinGen Malignant Hyperthermia Susceptibility Variant Curation Expert Panel,ClinGen" in EP_GeneList.xlsx 

Tested with a local run on EP Reports and succeeded with no errors.

**Comment by toneillbroad** [comment]
Needed to move the new changed EP_GeneList.xlsx file into the Clinvar Reports pipeline.

Did a local Docker image build, tag and push to clingen-dev cluster.

Will Monitor until I see a successful run in GCP.
